# Generated by Django 5.2.4 on 2025-07-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_zip',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=100)),
                ('room_duration', models.DecimalField(decimal_places=1, max_digits=2)),
                ('room_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.hotel')),
            ],
        ),
    ]
